In [8]:
import numpy as np

# 创建 3x4 的二维数组
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# 1. 打印数组属性
print("1. 数组属性:")
print("数组形状:", arr.shape)        # (3, 4)
print("数组维度:", arr.ndim)         # 2
print("数据类型:", arr.dtype)        # int32 或 int64（取决于系统）

# 2. 数组元素乘以2
arr_multiplied = arr * 2
print("\n2. 乘以2后的数组:")
print(arr_multiplied)

# 3. 重塑为 4x3 形状
arr_reshaped = arr.reshape(4, 3)
print("\n3. 重塑为4x3的数组:")
print(arr_reshaped)

1. 数组属性:
数组形状: (3, 4)
数组维度: 2
数据类型: int32

2. 乘以2后的数组:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

3. 重塑为4x3的数组:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
import numpy as np

# 创建 4x4 数组
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# 1. 提取第2行所有元素（索引从0开始，所以是索引1）
row_2 = array[1, :]
print("1. 第2行所有元素:", row_2)  # [5, 6, 7, 8]

# 2. 提取第3列所有元素（索引2）
col_3 = array[:, 2]
print("2. 第3列所有元素:", col_3)  # [3, 7, 11, 15]

# 3. 提取子数组（第1、2行和第2、3列）
sub_array = array[0:2, 1:3]
print("3. 子数组:")
print(sub_array)  # [[2, 3], [6, 7]]

# 4. 将大于10的元素替换为0
modified_array = array.copy()  # 创建副本，避免修改原始数组
modified_array[modified_array > 10] = 0
print("4. 修改后的数组:")
print(modified_array)

1. 第2行所有元素: [5 6 7 8]
2. 第3列所有元素: [ 3  7 11 15]
3. 子数组:
[[2 3]
 [6 7]]
4. 修改后的数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [11]:
import numpy as np

# 创建数组 A (3x2)
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# 创建数组 B (1x2)
B = np.array([10, 20])

print("数组A:")
print(A)
print("\n数组B:")
print(B)

# 1. 计算 A 和 B 的逐元素相加
sum_result = A + B
print("\n1. A + B:")
print(sum_result)

# 2. 计算 A 和 B 的逐元素相乘
multiply_result = A * B
print("\n2. A * B:")
print(multiply_result)

# 3. 计算 A 的每一行与 B 的点积
dot_products = np.dot(A, B)
print("\n3. A的每一行与B的点积:")
print(dot_products)

数组A:
[[1 2]
 [3 4]
 [5 6]]

数组B:
[10 20]

1. A + B:
[[11 22]
 [13 24]
 [15 26]]

2. A * B:
[[ 10  40]
 [ 30  80]
 [ 50 120]]

3. A的每一行与B的点积:
[ 50 110 170]
